### ISSUE TITLE
Request: make code CF10 compatible

### ISSUE THREAD

**Issue by aqlong** [jcberquist/aws-cfml#1]
Thanks for this code! I'm trying to use it on a CF10 project with DynamoDB. I modified the code locally to work around CF11-specific code, but am stuck on the parseQueryParams() method in the utils.cfc. 

If you could write that method to work work in CF10, I'd be happy to share the rest of my code that works with cf10. I wish I could upgrade, but it's not an option at this time.

**Comment by jcberquist** [comment]
If the issue is the `ArrayReduce()`, then I think it could be rewritten like so (untested):
```
public string function parseQueryParams( required struct queryParams, boolean encodeQueryParams = true, boolean includeEmptyValues = true ) {
    var sortedKeyArray = queryParams.keyArray();
    sortedKeyArray.sort( 'text' );
    var queryString = '';
    for ( var queryParamKey in sortedKeyArray ) {
      var encodedKey = encodeQueryParams ? encodeUrl( queryParamKey ) : queryParamKey;
      var encodedValue = encodeQueryParams && len( queryParams[ queryParamKey ] ) ? encodeUrl( queryParams[ queryParamKey ] ) : queryParams[ queryParamKey ];
      queryString = listAppend( queryString, encodedKey & ( includeEmptyValues || len( encodedValue ) ? ( '=' & encodedValue ) : '' ), '&' );        
    }
    return queryString;
}
```

**Comment by aqlong** [comment]
thanks @jcberquist !

That gave me enough to keep going and get everything mostly working on CF10. I have a lot more testing to do, but I was able to move forward...
