### ISSUE TITLE
Does this integrate with Cloudwatch?

### ISSUE THREAD

**Issue by redtopia** [jcberquist/aws-cfml#11]
Hey John, I love using your ST3 plugin for ACF/Lucee, and your quick responses to issues that come up, so I'm intrigued about this project.

I'm currently looking for a way to monitor the health of my Lucee apps using CloudWatch Events, which is new to me. Looks like I need to use the `put-events` AWS API call (https://docs.aws.amazon.com/cli/latest/reference/events/put-events.html)

Have you done this? I'm assuming this would be possible using your wrapper. Yes? No? Not sure? Thanks!

**Comment by redtopia** [comment]
Eh... I might still want to make CloudWatch api calls, but I just realized that if my app isn't working, it's because Lucee is probably dead, which means that I won't be able to use Lucee to make CloudWatch api calls. Doh!

I think I would need to make CloudWatch calls from Windows Powershell using the CloudWatch Agent. I believe I can send windows logs directly to CloudWatch using the agent, which might be how to do this.

Still learning! :)

**Comment by jcberquist** [comment]
@redtopia Thanks! 

You could use this library to make requests to the CloudWatch API, as it can be used to sign any AWS HTTP request. But I agree, I would use the CloudWatch agent to send metrics to CloudWatch. That is what we do, albeit on Linux.
