### ISSUE TITLE
Question: S3 Upload speed very slow

### ISSUE THREAD

**Issue by a1development** [jcberquist/aws-cfml#15]
I guess it s not an issue with aws-cfml but i would be interested to see if this is normal behavior.
It takes about 1 second to upload 100kb to s3. I tested it with a 1,7mb image at first wich took about 18 seconds. I i do the same on the same server with the web interface of S3 it takes under 1 second. 

Any experiences / ideas how to speed that up?

**Comment by jcberquist** [comment]
I am sorry, but I am not really sure what is going on here. I don't experience slowdowns like this. 

Under the hood `aws-cfml` is using cfhttp to perform the HTTP PUT request to S3. My first thought is that there is some issue there. Have you tested cfhttp on the same server making generic SSL requests? I think I would start there. I do think there are situations where cfhttp can end up performing poorly.
