### ISSUE TITLE
PutObject - PDF

### ISSUE THREAD

**Issue by doodi-v1** [jcberquist/aws-cfml#25]
By any chance do you have a sample using the S3.putObject request? I have a page that accepts an upload of a PDF from a client, reads the file contents in using fileReadBinary(), and I cannot figure out the correct usage of the putObject() call. I've tried passing the file contents raw, with toBinary, with toBase64, with toBinary and then toBase64, even tried various encodeForXML as the message I'm receiving back references an Bad Request - Invalid XML.

	"S3RESPONSE":{
		"responseHeaders":{
			"Explanation":"Bad Request",
			"Connection":"close",
			"Transfer-Encoding":"chunked",
			"Date":"Thu, 29 Aug 2019 20:01:21 GMT",
			"Server":"AmazonS3",
			"x-amz-id-2":"p3BuX1V4L/f0zexSJ+crfZxZQI1M+jj6XBlCm/KcCYj8lPeDPpgGHwkk4mGofUyavACP6H9c/iU=",
			"Content-Type":"application/xml",
			"Status_Code":400,
			"x-amz-request-id":"FBA1B419A83083C3",
			"Http_Version":"HTTP/1.1"
		},
		"rawData":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>FBA1B419A83083C3</RequestId><HostId>p3BuX1V4L/f0zexSJ+crfZxZQI1M+jj6XBlCm/KcCYj8lPeDPpgGHwkk4mGofUyavACP6H9c/iU=</HostId></Error>",
		"statusCode":400,
		"responseTime":580.0,
		"error":{
			"Message":"The XML you provided was not well-formed or did not validate against our published schema",
			"Code":"MalformedXML",
			"RequestId":"FBA1B419A83083C3",
			"HostId":"p3BuX1V4L/f0zexSJ+crfZxZQI1M+jj6XBlCm/KcCYj8lPeDPpgGHwkk4mGofUyavACP6H9c/iU="
		}
	}

**Comment by jcberquist** [comment]
Very interesting. It sounds to me like you are doing it the way I intended:
```cfc
aws.s3.putObject('bucket', 'key', binaryData);
```
I tested this with a PDF file and I could successfully upload to buckets in a couple of regions.

But in your case it looks to me like AWS is not viewing the request as a PUT object request, but one where it expected an XML body.

Could I ask whether you created your bucket recently, and what region it is in?

**Comment by doodi-v1** [comment]
I am providing contentType="application/pdf" - maybe that is the issue?  I did not try leaving that parameter off. I have no idea where XML is coming from; I was assuming something under the curtains was using XML and the binary data was confusing things. I'll try some more experiments tomorrow. I was able to upload using cffile with the S3 credentials so I know the bucket and credentials work.

**Comment by doodi-v1** [comment]
Update. I removed the contentType parameter and it worked. I don't know why I did not try that before, but that was the issue.

**Comment by jcberquist** [comment]
Interesting, I would love to know the function call signature you used - I tested it with a content type after your post above, and it still worked for me.

**Comment by doodi-v1** [comment]
I didn't do anything with a signature:
		fileWrite("s3://#variables.awsAT.api.getcredentials().getcredentials().awsKey#:#variables.awsAT.api.getcredentials().getcredentials().awsSecretKey#@s4-gateway-docs/#local.objectKey.toList('/')#",toBinary(local.uploadedFileContent));

I'll add, in my limited testing, using native fileWrite uploaded a 213K PDF in 3-4 seconds, aws-cfml putObject did in under a second in all my tests.

**Comment by jcberquist** [comment]
Sorry, I meant something like the following (with the aws-cfml library):
```cfc
aws.s3.putObject(
    Bucket = 'bucket',
    ObjectKey = 'objectkey',
    FileContent = binaryData,
    ContentType = 'application/pdf'
);
```
When I tested, the content type did get set correctly for me.

**Comment by doodi-v1** [comment]
Your sample is almost identical to what I was using - the values were different except for ContentType.

**Comment by doodi-v1** [comment]
Ok, I am totally baffled this morning. Thinking there was a case issue with the variable names and/or ContentType value, I started tweaking things. Now everything is working. Even the code I started with before I got in this morning??? Giving up for now. You can close this.

**Comment by jcberquist** [comment]
Ok, hopefully it doesn't recur.
