### ISSUE TITLE
Dynamodb partiql

### ISSUE THREAD

**Issue by victorbvieira** [jcberquist/aws-cfml#54]
hello, I tried to implement the dynamodb partiql in the library, as it seemed simpler to run queries.
but, I was not successful.
Could you implement a method that uses dynamodb partiql ? https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.html

**Comment by jcberquist** [comment]
Hi in `v1.21.0` I added support for `ExecuteStatement`, `BatchExecuteStatement`, and `ExecuteTransaction`. Let me know if this helps!

To give a simple example:

```cfc
aws = new awscfml.aws();

statement = "
SELECT *
FROM Orders
WHERE OrderID = ?
"
res = aws.dynamodb.executeStatement( statement = statement, parameters = [ 100 ] );

writeDump( res );
```

**Comment by victorbvieira** [comment]
Very Tks ;)
