### ISSUE TITLE
How to put a file to Wasabi S3?

### ISSUE THREAD

**Issue by artknight** [jcberquist/aws-cfml#55]
I am trying to put a file to `s3.wasabisys.com` instead of amazon. Their compatibility with Amazon is 100%. 

Where is the code below can i specify the different end-point?

```
aws = new aws(
    awsKey = 'YOUR_PUBLIC_KEY',
    awsSecretKey = 'YOUR_PRIVATE_KEY',
    defaultRegion = 'us-east-1'
);

zipFileData = fileReadBinary('myfile.zip');
aws.s3.putObject(bucket = 'mybucket', objectKey = 'xxxx', fileContent = zipFileData);
```

**Comment by jcberquist** [comment]
Hi, you should be able to do this by using the `constructorArgs` with a host setting for s3:
```cfc
aws = new aws(
    awsKey = 'YOUR_PUBLIC_KEY',
    awsSecretKey = 'YOUR_PRIVATE_KEY',
    defaultRegion = 'us-east-1',
    constructorArgs = {
        s3: {
            host: 's3.wasabisys.com'
        }
    }
);
```

**Comment by artknight** [comment]
@jcberquist perfect! Thank you Sir!

**Comment by artknight** [comment]
@jcberquist sorry to bother ... is there any way to create folders within buckets? If yes, what would the code for that look like?

**Comment by artknight** [comment]
Yes Sir, I had found a post talking about it and got it resolved. Thank you!
