### ISSUE TITLE
Secret Manager

### ISSUE THREAD

**Issue by pererasu** [jcberquist/aws-cfml#58]
Hi

For the secret manager usage:

response = aws.secretsmanager.getSecretValue( 'YourSecretId' );
secretValue = response.data.SecretString;

is YourSecretId the ARN of the secret and SecretString the Secret Key?

Suppose my values in secret manager as follows:

Secret key | Secret value

password | xxxxxxxxxxxx

YourSecretId == arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:MyRDSSecret-C4t4tS
SecretString == password

response = aws.secretsmanager.getSecretValue( 'arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:MyRDSSecret-C4t4tS' );
secretValue = response.data.password;

does that look about right?

**Comment by jcberquist** [comment]
Hi, I haven't actually used the secret manager via this library, it was added by @mjclemente - he would know for sure. But what you have looks reasonable to me, I believe `getSecretValue` can take a full ARN as the `SecretId`. In the docs here: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html it mentions that SecretId can be "The ARN or name of the secret to retrieve." You could also take a look at Matt's blog post on this: https://blog.mattclemente.com/2022/01/17/connecting-to-aws-secrets-manager-cfml/

**Comment by pererasu** [comment]
Thanks for the response. Much appreciated.
