### ISSUE TITLE
how to get the size of a bucket?

### ISSUE THREAD

**Issue by artknight** [jcberquist/aws-cfml#59]
Hi,
sorry to be posting this question here.. :)

I am using the s3 hookup of your library and I need to be able to get the size in MB or GB of a specific bucket. How would I do that?

Thanks in advance!
Art

**Comment by ddspringle** [comment]
Hey Art,

   Looking at the code my assumption would be that you would need to use either the listBucket or listBucketV2 function in the S3 service cfc to get a list of all the objects in the bucket. From that data you should be able to arrayReduce() the file sizes to get the total and from that you can divide as needed to get MB/GB.

   From wnat I recall I don’t believe there is a method in the AWS SDK or API to just get the total size of a bucket, but I also haven’t looked at either in awhile so will defer on that to someone who may. In either case that method, if it exists, is not currently exposed in this library.

HTH

— Denny

**Comment by artknight** [comment]
@ddspringle Thank you!
