### ISSUE TITLE
Would love some help

### ISSUE THREAD

**Issue by kellymatthews-cfwt** [jcberquist/aws-cfml#81]
No matter what I do I am getting SignatureDoesNotMatch as a response.  We are initially just trying to use the sts service to get an access token.  If I run it via Postman it works, same with CURL.  @jcberquist are you open to consulting, would be happy to pay for your time.

**Comment by jcberquist** [comment]
Could you show me how you are trying to use the library with some example code (with appropriate redactions)?

**Comment by kellymatthews-cfwt** [comment]
Sure here's the code... Not sure why my spacing in the cfscript tag is all wonky but everything is on a separate line. 
  I xx'd out my keys. But they are correct. Working fine in Postman.   In post man we get back our Token that we then will use on the next step.  But for some reason outside of Postman we always get this error. 
`<cfset awsService = `application.wirebox.getInstance("awsService")>`

`<cfscript>
	service = 'sts';
	host = 'sts.amazonaws.com';
	region = 'us-east-1';
	httpMethod = 'get';
	path = '/';
	queryParams = {};
	queryParams['Version'] = '2011-06-15';
	queryParams['Action'] = 'AssumeRole';
	queryParams['RoleSessionName'] = 'Test';
	queryParams['RoleArn'] = 'arn:aws:iam::729841562454:role/Cleanrun.SellingPartnerAPI_Role';
	queryParams['DurationSeconds'] = '3600';
	headers = {};
	body = '';
	awsCredentials = {};
	awsCredentials['awsKey'] = 'XXX';
	awsCredentials['awsSecretKey'] = 'XXX';
	awsCredentials['token'] = '';
</cfscript>`

`<cfset` response = awsService.api.call(service, host, region, httpMethod, path, queryParams, headers, body, awsCredentials)>`

` <cfdump var="#response#" label="Response">` 

The response I get is:
`<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"> <Error> <Type>Sender</Type> <Code>SignatureDoesNotMatch</Code> <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message> </Error> <RequestId>38a27a63-0370-4e72-9da7-5a1e376daccb</RequestId> </ErrorResponse>`

Dumped out the args and they look fine.

**Comment by jcberquist** [comment]
My first thought is with the httpMethod - you have it as lower case, but I am guessing that in order for the canonical request to match what AWS calculates it might need to be uppercase. Could you try it with `httpMethod = 'GET'`?

**Comment by kellymatthews-cfwt** [comment]
Updated that.  Unfortunately that was not the issue. Same error.

**Comment by kellymatthews-cfwt** [comment]
![Screen Shot 2023-06-22 at 6 29 41 PM](https://github.com/jcberquist/aws-cfml/assets/130575410/946b1401-262d-44e6-87d4-53d4abc50794)
![Screen Shot 2023-06-22 at 6 30 20 PM](https://github.com/jcberquist/aws-cfml/assets/130575410/e7087864-1602-43c6-b389-d93cf0c1c5fc)

**Comment by kellymatthews-cfwt** [comment]
A couple screen shots that may help. XXX'd my secret key.

**Comment by jcberquist** [comment]
In your screenshot you have: 
```
path = '';
```
In your example code you had:
```
path = '/';
```
it should be the latter, can you confirm that?

**Comment by kellymatthews-cfwt** [comment]
Ok so that was it. But I had tried it both ways before so I think it was actually the GET I just didn't change path back to / after changing GET! You are awesome! :) Thank you so much! I'm sure i'll be back! 👍

**Comment by jcberquist** [comment]
Great! Glad it is resolved.
