### ISSUE TITLE
CFML parsing error when creating a new object

### ISSUE THREAD

**Issue by clagi1** [jcberquist/aws-cfml#88]
There is a parsing error when trying to create the awscfml object in Coldfusion 2018.
It looks like a trailing comma was introduced in the arguments of the listSecrets function in the latest build (1.34.0):

https://github.com/jcberquist/aws-cfml/blob/master/services/secretsmanager.cfc#L187

**Comment by jcberquist** [comment]
Thanks for reporting this!
